### ISSUE TITLE
I would like to make a logo of the app

### ISSUE THREAD

**Issue by stlyash** [vilsi12/Red-Hat-Mobil-App#10]
I mean app icon

**Comment by kmryashasvi** [comment]
![Screenshot_20210313-111803.png](https://user-images.githubusercontent.com/66861659/111020765-36d02d80-83ee-11eb-8ef5-4a19c81ac6da.png)


Is it okay?

**Comment by kmryashasvi** [comment]
![red 2](https://user-images.githubusercontent.com/66861659/111028842-5f245000-841f-11eb-8079-df462ce74118.png)

**Comment by kmryashasvi** [comment]
I cannot make it smooth more than that

**Comment by vilsi12** [comment]
Hello give your logo i will do

**Comment by stlyash** [comment]
see the above comment
the latest one
that is final

**Comment by vilsi12** [comment]
you can file in repo so i can merge and not ss send png i will update

**Comment by stlyash** [comment]
Please check the above PR for the logo
