### ISSUE TITLE
Put icon in registration page for email and password

### ISSUE THREAD

**Issue by vilsi12** [vilsi12/Red-Hat-Mobil-App#3]
I have put for email you have to not change that

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by vilsi12** [comment]
Hello you can contact me before starting

**Comment by Akash20x** [comment]
Kindly, assign this issue to anyone else.
I started working on other issue and didn't time left for this issue.

**Comment by vilsi12** [comment]
ok

**Comment by Devanshi-karthik** [comment]
Hey! I'd like to take this up if it's not been resolved.

**Comment by vilsi12** [comment]
I have assign check the video before on change in registration and login
https://youtu.be/t1Fo3KUx1_k

**Comment by Devanshi-karthik** [comment]
> I have assign check the video before on change in registration and login
> https://youtu.be/t1Fo3KUx1_k

Yes. I've gone through it . Will send you the pr asap.
