### ISSUE TITLE
Can you add to the readme of what this project is about?

### ISSUE THREAD

**Issue by Rukmini-Meda** [vilsi12/Red-Hat-Mobil-App#5]
Hello

I am a Flutter developer. I have worked with a couple of projects before as part of a small internship and an open source program. Can you let me know what this project is about so that I can see what I can contribute to it as part of cross winter of code?

Thanks!

**Comment by vilsi12** [comment]
Check in this I have explain all the topic https://youtu.be/t1Fo3KUx1_k
