### ISSUE TITLE
add banner of crosswoc to the readme file

### ISSUE THREAD

**Issue by kmryashasvi** [vilsi12/Red-Hat-Mobil-App#7]
I will add banner of crosswoc to the readme file so that, People will know it is associated to crosswoc.
Moreover, I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

**Comment by vilsi12** [comment]
You have to banner and make a redme good see in link

**Comment by kmryashasvi** [comment]
I just followed you

**Comment by vilsi12** [comment]
ok

**Comment by kmryashasvi** [comment]
if you don't need any further modifications, this issue can be closed after merging the above pull request

**Comment by vilsi12** [comment]
Remove that crosswoc banner other is good

**Comment by kmryashasvi** [comment]
hahaha, 
matlab jiss kaam ke iye issue banaya wahi hata doon?
okay no problem

**Comment by kmryashasvi** [comment]
I have updated,
Please have a look once again

**Comment by vilsi12** [comment]
Yes I don't think its important but you have done good

**Comment by kmryashasvi** [comment]
I have done the required changes,
Please have a look

**Comment by kmryashasvi** [comment]
Why aren't you merging the PR?

**Comment by vilsi12** [comment]
add dicord  link also  i will merge
Thank you great

**Comment by kmryashasvi** [comment]
Then please provide me the link. 
I don't have any discord link

**Comment by vilsi12** [comment]
Its in youtube link take and you can join

**Comment by kmryashasvi** [comment]
I have done the changes,
Please have a look

**Comment by kmryashasvi** [comment]
Can I close this issue now? or you need it?
